-- Write your PostgreSQL query statement below
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY AS SALARY
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
WHERE (D.NAME, E.SALARY) IN (
    SELECT D.NAME, MAX(E.SALARY)
    FROM EMPLOYEE E
    JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
    GROUP BY D.NAME
);